# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=20)),
                ('language_code', models.CharField(db_index=True, max_length=5)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'db_table': 'language',
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('timezone', models.CharField(db_index=True, default='UTC', max_length=20)),
                ('zabbix_user_id', models.IntegerField(default=0)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserLanguage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userlanguage',
            unique_together=set([('language', 'language_code')]),
        ),
    ]
