# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20171101_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(db_index=True, default='UTC', max_length=20),
        ),
    ]
