# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20171110_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
            ],
            options={
                'verbose_name': 'bad username',
                'verbose_name_plural': 'bad username',
                'db_table': 'bad_username',
            },
        ),
    ]
