# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20171121_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badusername',
            options={'verbose_name': 'bad username', 'verbose_name_plural': 'bad usernames'},
        ),
    ]
